config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('gerenciador_de_ebd.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^',include('escola.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

gerenciador_de_ebd/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

escola/models.py
from datetime import date, datetime
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


class Classe(models.Model):
    '''
    Definição da Classe da ebd
    '''

    ADULTO = 'adulto'
    JOVENS = 'jovens'
    ADOLESCENTES = 'adolescentes'
    JUVENIS = 'juvenis'
    JUNIORES = 'juniores'
    MATERNAL = 'maternal'

    FAIXA_TYPES = (
        (ADULTO, _('Adulto')),
        (JOVENS, _('Jovens')),
        (ADOLESCENTES, _('13 e 14 anos')),
        (JUVENIS, _('15 a 17 anos')),
        (JUNIORES, _('9 e 10 anos')),
        (MATERNAL, _('3 e 4 anos')),
    )

    numero = models.CharField(max_length=50, blank=False)
    departamento = models.ForeignKey(to='Departamento', blank=True, null=True)
    faixa = models.CharField(choices=FAIXA_TYPES, max_length=50, default=ADULTO)

    @property
    def professor(self):
        return self.componente_set.get(tipo=Componente.PROFESSOR)

    @property
    def adjuntos(self):
        return self.componente_set.filter(tipo=Componente.ADJUNTO)

    @property
    def qtd_alunos(self):
        return len(self.componente_set.filter(tipo=Componente.ALUNO))

    def __str__(self):
        return self.numero

    class Meta:
        ordering = ('numero', 'departamento', 'faixa')


class Departamento(models.Model):
    '''
    Representa um departamento da escola
    '''
    nome = models.CharField(max_length=100)
    coordenador = models.ForeignKey(to='Componente', blank=True, null=True)

    class Meta:
        ordering = ('nome',)

    def __unicode__(self):
        return '%s' % self.nome

    def __str__(self):
        return '%s' % self.nome


class Componente(models.Model):
    '''
    Representa um componente da escola dominical
    '''

    DIRIGENTE = 'dirigente'
    VICEDIRIGENTE = 'vice-dirigente'
    SECRETARIO = 'secretario'
    VICESECRETARIO = 'vice-secretario'
    TESOUREIRO = 'tesoureiro'
    VICETESOUREIRO = 'vice-tesoureiro'
    VICECOORDENADORA = 'vice-coordenadora'
    PROFESSOR = 'professor'
    ADJUNTO = 'adjunto'
    SECRETARIOLOCAL = 'secretario-local'
    ALUNO = 'aluno'
    COORDENADORA = 'coordenadora'

    COMPONENT_TYPES = (
        (DIRIGENTE, _('Dirigente')),
        (VICEDIRIGENTE, _('Vice-dirigente')),
        (SECRETARIO, _('Secretario')),
        (VICESECRETARIO, _('Vice-secretário')),
        (TESOUREIRO, _('Tesoureiro')),
        (VICETESOUREIRO, _('Vice-tesoureiro')),
        (VICECOORDENADORA, _('Vice-coordenadora')),
        (PROFESSOR, _('Professor')),
        (ADJUNTO, _('Adjunto')),
        (SECRETARIOLOCAL, _('Secretario Local')),
        (ALUNO, _('Aluno')),
        (COORDENADORA, _('Coordenadora')),
    )

    MASCULINO = 'masculino'
    FEMININO = 'feminino'
    SEXO_TYPES = (
        (MASCULINO, _('Masculino')),
        (FEMININO, _('Feminino')),
    )

    cartao_membro = models.IntegerField()
    classe = models.ForeignKey(to='Classe', blank=True, null=True)
    tipo = models.CharField(_('Função'), choices=COMPONENT_TYPES, default=ALUNO, max_length=50)
    nome = models.CharField(max_length=100)
    sexo = models.CharField(choices=SEXO_TYPES, max_length=15, blank=True, null=True)
    nascimento = models.DateField(blank=True, null=True)
    endereco = models.CharField(_('Endereço'), max_length=200, blank=True, null=True)
    complemento_end = models.CharField(_('Complemento'), max_length=100, blank=True, null=True)
    bairro = models.CharField(max_length=100, blank=True, null=True)
    cep = models.CharField(max_length=50, blank=True, null=True)
    cidade = models.CharField(max_length=100, blank=True, null=True)
    uf = models.CharField(_('UF'), max_length=50, blank=True, null=True)
    telefone = models.CharField(max_length=50, blank=True, null=True)
    celular = models.CharField(max_length=50, blank=True, null=True)
    email = models.CharField(max_length=100, blank=True, null=True)
    estado_civil = models.CharField(_('Estado Civil'), max_length=50, blank=True, null=True)

    class Meta:
        ordering = ('nome',)


class CadernetaGeral(models.Model):
    NORMAL = 'normal'
    MISSIONARIA = 'manha-missionaria'
    UNICA = 'classe-unica'
    ANIMADA = 'escola-animada'
    
    ESCOLA_TYPES = (
        (NORMAL, _('Normal')),
        (MISSIONARIA, _('Manhã Missionária')),
        (UNICA, _('Classe única')),
        (ANIMADA, _('Escola Animada'))
    )

    tipo = models.CharField(_('Tipo'), choices=ESCOLA_TYPES, default=NORMAL, max_length=50)
    data = models.DateField(default=date.today)

    def __str__(self):
        data_str = self.data.strftime("%d/%m/%Y")
        return data_str


class Caderneta(models.Model):

    classe = models.ForeignKey(to='Classe', related_name='classe', on_delete=models.CASCADE)
    domingo = models.ForeignKey(to='CadernetaGeral', related_name='caderneta_geral')
    presentes = models.IntegerField(blank=True, null=True, default=0)
    visitantes = models.IntegerField(blank=True, null=True, default=0)
    matriculados = models.IntegerField(blank=True, null=True, default=0)
    biblias = models.IntegerField(blank=True, null=True, default=0)
    professor = models.IntegerField(blank=True, null=True, default=0)
    adjuntos = models.IntegerField(blank=True, null=True, default=0)

    @property
    def frequencia(self):
        return (self.presentes / self.matriculados) * 100

    @property
    def atendimento(self):
        return self.presentes + self.visitantes + self.professor + self.adjuntos

    class Meta:
        ordering = ('classe',)

gerenciador_de_ebd/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

gerenciador_de_ebd/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

gerenciador_de_ebd/templates/pages/about.html
{% extends "base.html" %}

gerenciador_de_ebd/templates/pages/caderneta-details.html
{% extends "base.html" %}

{% load static i18n %}
{% load rest_framework %}
{% block css %}
{{ block.super }}
{% endblock %}

{% block content %}
<div class="right_col" role="main">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
            <h2>Caderneta</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <form method="POST" id="caderneta-details" action="{% url 'caderneta_details' pk=componente.pk %}" data-parsley-validate class="form-horizontal form-label-left">
            {% render_form serializer template_pack='rest_framework/horizontal' %}
            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-5">
                <a class="btn btn-primary" type="button" href="{% url url_redirect %}">Cancelar</a>
                <button id="caderneta-save" type="submit" class="btn btn-success">Salvar</button>
              </div>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

gerenciador_de_ebd/templates/pages/caderneta-new-home.html
{% extends "base.html" %}

{% load static i18n %}
{% load rest_framework %}
{% block css %}
{{ block.super }}
{% endblock %}

{% block content %}
<div class="right_col" role="main">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
            <h2>Nova Caderneta</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <form method="POST" id="caderneta-new-form" action="{% url 'caderneta_new' %}" data-parsley-validate class="form-horizontal form-label-left">
            {% comment %} {% render_form serializer template_pack='rest_framework/horizontal' %} {% endcomment %}
              {{ form }}
            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-5">
                <a class="btn btn-primary" type="button" href="{% url url_redirect %}">Cancelar</a>
                <button id="componente-new-save" type="submit" class="btn btn-success">Salvar</button>
              </div>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

gerenciador_de_ebd/templates/pages/caderneta.html
{% extends "base.html" %}

{% load static i18n %}
{% block css %}
{{ block.super }}
  <link href="{% static 'css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
<div class="right_col" role="main">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Caderneta</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <label for="data_caderneta">Domingo: </label>
            <select name="domingos" id="domingos">
              <option value="-">-</option>
              {% for domingo in domingos %}
                <option value="{{ domingo }}">{{ domingo.data }}</option>
              {% endfor %}
            </select>
          </div>
        <div class="x_content">
          <table id="classes-datatable" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>Classe</th>
                <th>Presentes</th>
                <th>Visitantes</th>
                <th>Bíblias</th>
                <th>Matriculados</th>
                <th>Professor</th>
                <th>Adjuntos</th>
                <th>Atendimento</th>
                <th>Frequência</th>
                <th>Ações</th>
              </tr>
            </thead>

            <tbody>
              {% for caderneta in cadernetas %}
                <tr>
                  <td>{{ caderneta.classe.numero }}</td>
                  <td>{{ caderneta.presentes }}</td>
                  <td>{{ caderneta.visitantes }}</td>
                  <td>{{ caderneta.biblias }}</td>
                  <td>{{ caderneta.matriculados }}</td>
                  <td>{{ caderneta.professor }}</td>
                  <td>{{ caderneta.adjuntos }}</td>
                  <td>{{ caderneta.atendimento }}</td>
                  <td>{{ caderneta.frequencia }}</td>
                  <td>
                    <a type="button" class="btn btn-default" href="" id="editar-caderneta">
                        <i class="fa fa-edit"></i>
                    </a>
                    <a type="button" class="btn btn-danger" href="" id="excluir-caderneta">
                        <i class="fa fa-times"></i>
                    </a>
                  </td>
                </tr>
              {% endfor %}
            </tbody>

          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block javascript %}
{{ block.super }}
  <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'js/classes.js' %}"></script>
{% endblock javascript %}

gerenciador_de_ebd/templates/pages/classe-details.html
{% extends "base.html" %}

{% load static i18n %}
{% load rest_framework %}
{% block css %}
{{ block.super }}
{% endblock %}

{% block content %}
<div class="right_col" role="main">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
            <h2>Classe</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <form method="POST" id="classe-form" action="{% url 'classe-detail' pk=classe.pk %}" data-parsley-validate class="form-horizontal form-label-left">
              {% render_form serializer template_pack='rest_framework/horizontal' %}
            
            <div class="ln_solid"></div>
            <h4>Professores</h4>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">Professor:</label>
              <label class="control-label col-md-3 col-sm-3 col-xs-12">{{ classe.professor.nome }}</label>
            </div>
            <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12">Adjuntos:</label>
                {% for adjunto in classe.adjuntos %}
                  <label class="control-label col-md-3 col-sm-3 col-xs-12">{{ adjunto.nome }}{% if not forloop.last %},{% endif %}</label>
                {% endfor %}
              </div>
            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-5">
                <a class="btn btn-primary" type="button" href="{% url 'classes' %}">Cancelar</a>
                <button id="classe-save" type="submit" class="btn btn-success">Salvar</button>
              </div>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

gerenciador_de_ebd/templates/pages/classe-new.html
{% extends "base.html" %}

{% load static i18n %}
{% load rest_framework %}
{% block css %}
{{ block.super }}
{% endblock %}

{% block content %}
<div class="right_col" role="main">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
            <h2>Classe</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <form method="POST" id="classe-new-form" action="{% url 'classe_new' %}" data-parsley-validate class="form-horizontal form-label-left">
              {% render_form serializer template_pack='rest_framework/horizontal' %}

            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-5">
                <a class="btn btn-primary" type="button" href="{% url url_redirect %}">Cancelar</a>
                <button id="classe-new-save" type="submit" class="btn btn-success">Salvar</button>
              </div>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

gerenciador_de_ebd/templates/pages/classes.html
{% extends "base.html" %}

{% load static i18n %}
{% block css %}
{{ block.super }}
  <link href="{% static 'css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
<div class="right_col" role="main">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Classes</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <table id="classes-datatable" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th></th>
                <th>Numero</th>
                <th>Departamento</th>
                <th>Faixa</th>
                <th>Professor</th>
                <th>Total de Alunos</th>
              </tr>
            </thead>

            <tbody>
              {% for classe in classes %}
                <tr>
                  <td><a type="button" class="btn btn-default" href="{% url 'classe-detail' pk=classe.pk %}" id="classe-details">Detalhes</a></td>
                  <td>{{ classe.numero }}</td>
                  <td>{{ classe.departamento.nome }}</td>
                  <td>{{ classe.get_faixa_display }}</td>
                  <td>{{ classe.professor.nome }}</td>
                  <td>{{ classe.qtd_alunos }}</td>
                </tr>
              {% endfor %}
            </tbody>

          </table>
        </div>
        <div>
          <a type="button" class="btn btn-primary" href="{% url 'classe_new' %}" id="nova-classe">Nova</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block javascript %}
{{ block.super }}
  <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'js/classes.js' %}"></script>
{% endblock javascript %}

gerenciador_de_ebd/templates/pages/componente-details.html
{% extends "base.html" %}

{% load static i18n %}
{% load rest_framework %}
{% block css %}
{{ block.super }}
{% endblock %}

{% block content %}
<div class="right_col" role="main">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
            <h2>Componente</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <form method="POST" id="componente-form" action="{% url 'componente-detail' pk=componente.pk %}" data-parsley-validate class="form-horizontal form-label-left">
              {% render_form serializer template_pack='rest_framework/horizontal' %}

            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-5">
                <a class="btn btn-primary" type="button" href="{% url url_redirect %}">Cancelar</a>
                <button id="componente-save" type="submit" class="btn btn-success">Salvar</button>
              </div>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

gerenciador_de_ebd/templates/pages/componente-new.html
{% extends "base.html" %}

{% load static i18n %}
{% load rest_framework %}
{% block css %}
{{ block.super }}
{% endblock %}

{% block content %}
<div class="right_col" role="main">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
            <h2>Componente</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <form method="POST" id="componente-new-form" action="{% url 'componente_new' %}" data-parsley-validate class="form-horizontal form-label-left">
              {% render_form serializer template_pack='rest_framework/horizontal' %}

            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-5">
                <a class="btn btn-primary" type="button" href="{% url url_redirect %}">Cancelar</a>
                <button id="componente-new-save" type="submit" class="btn btn-success">Salvar</button>
              </div>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

gerenciador_de_ebd/templates/pages/componentes.html
{% extends "base.html" %}

{% load static i18n %}
{% block css %}
{{ block.super }}
  <link href="{% static 'css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
<div class="right_col" role="main">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>{{ title }}</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <table id="professores-datatable" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th></th>
                <th>Nome</th>
                <th>Classe</th>
                <th>Função</th>
              </tr>
            </thead>

            <tbody>
              {% for componente in componentes %}
                <tr>
                  <td><a type="button" class="btn btn-default" href="{% url 'componente-detail' pk=componente.pk %}" id="componente-details">Detalhes</a></td>
                  <td>{{componente.nome}}</td>
                  <td>{{componente.classe.numero}}</td>
                  <td>{{componente.get_tipo_display}}</td>
                </tr>
              {% endfor %}
            </tbody>

          </table>
        </div>
        <div>
          <a type="button" class="btn btn-primary" href="{% url 'componente_new' %}" id="novo-componente">Novo</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block javascript %}
{{ block.super }}
  <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'js/componentes.js' %}"></script>
{% endblock javascript %}

gerenciador_de_ebd/templates/pages/departamentos.html
{% extends "base.html" %}

{% load static i18n %}
{% block css %}
{{ block.super }}
  <link href="{% static 'css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
<div class="right_col" role="main">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Departamentos</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <table id="departamentos-datatable" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>Departamento</th>
                <th>Coordenador</th>
              </tr>
            </thead>

            <tbody>
              {% for dep in departamentos %}
                <tr>
                  <td>{{dep.nome}}</td>
                  <td>{{dep.coordenador.nome}}</td>
                </tr>
              {% endfor %}
            </tbody>

          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block javascript %}
{{ block.super }}
  <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'js/departamentos.js' %}"></script>
{% endblock javascript %}

gerenciador_de_ebd/templates/pages/domingo-new.html
{% extends "base.html" %}

{% load static i18n %}
{% load rest_framework %}
{% block css %}
{{ block.super }}
{% endblock %}

{% block content %}
<div class="right_col" role="main">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
            <h2>Novo Domingo</h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <form method="POST" id="domingo-new-form" action="{% url 'domingo_new' %}" data-parsley-validate class="form-horizontal form-label-left">
              {% render_form serializer template_pack='rest_framework/horizontal' %}

            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-5">
                <a class="btn btn-primary" type="button" href="{% url url_redirect %}">Cancelar</a>
                <button id="domingo-new-save" type="submit" class="btn btn-success">Salvar</button>
              </div>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

gerenciador_de_ebd/templates/pages/home.html
{% extends "base.html" %}

gerenciador_de_ebd/templates/pages/professores.html
{% extends "base.html" %}

{% load static i18n %}
{% block css %}
{{ block.super }}
  <link href="{% static 'css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
<div class="right_col" role="main">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Professores</h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <table id="professores-datatable" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Classe</th>
                <th>Função</th>
              </tr>
            </thead>

            <tbody>
              {% for professor in professores %}
                <tr>
                  <td>{{professor.nome}}</td>
                  <td>{{professor.classe.numero}}</td>
                  <td>{{professor.get_tipo_display}}</td>
                </tr>
              {% endfor %}
            </tbody>

          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block javascript %}
{{ block.super }}
  <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'js/professores.js' %}"></script>
{% endblock javascript %}